repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: ruff check --fix
        language: system
        types: [python]
        exclude: "migrations/"

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
        exclude: "migrations/"

      - id: ty
        name: ty type check
        entry: ty check .
        language: system
        types: [python]
        pass_filenames: false
